### ISSUE TITLE
CustomNpcExclusions not registering download

### ISSUE THREAD

**Issue by DezraeBlue** [Esca-MMC/CustomNPCExclusions#1]
trying to install ridgeside village for stardew valley and the only issue i am having is i am unable to get customnpcexclusions to register it is in the mod file.
[SMAPI log (c15d56edfa1f4b639a73473d148acb08).txt](https://github.com/Esca-MMC/CustomNPCExclusions/files/11483353/SMAPI.log.c15d56edfa1f4b639a73473d148acb08.txt)

**Comment by Esca-MMC** [comment]
Sorry about the delay. For future reference, I'd recommend asking for help in one of Stardew's communities (Discord, Reddit, etc) for this kind of issue.

According to the log file, SMAPI didn't see any files related to Custom NPC Exclusions in your mod folders. It's possible you placed the mod somewhere else, or within another mod's folder.
